### ISSUE TITLE
Allow for Grace Hopper builds

### ISSUE THREAD

**Issue by diehlpk** [G-071/octotiger-spack#1]
On Grace Hopper, we want to use SVE since it is an ARM CPU. However, that requires C++ 20.

>> 146    CMake Error at CMakeLists.txt:826 (message):
     147      SVE builds with std::experimental::simd require C++20.  Please set
     148      OCTOTIGER_WITH_CXX20=ON
     149
     150

But we do not support CUDA builds with C++ 20

  >> 127    CMake Error at CMakeLists.txt:128 (message):
     128      CUDA builds with C++20 are not supported right now

On the other side CUDA  >=12 supports C++ 20.

Can we fix that?

**Comment by G-071** [comment]
I think we can close this as #3 added support for C++20 to the spack package.
 
That being said, using SVE in the GPU builds is still problematic (see explanation in #7 ), however, that compilation issue is not directly related to the actual spack package in this repository.
